"use client";

import "@mantine/core/styles.css";
import type { Metadata } from "next";
import { theme } from "./utils/theme";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { Electrolize } from "next/font/google";

const electrolize = Electrolize({ weight: "400", subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
        {/* remove white border */}
        <style>{`
          html, body {
            margin: 0;
            padding: 0;
          }
        `}</style>
      </head>
      <body className={electrolize.className} style={{ background: "#060e11" }}>
        <MantineProvider theme={theme}>{children}</MantineProvider>
      </body>
    </html>
  );
}
